version: 2.51.04.{build}

os: Visual Studio 2015

branches:
  except:
    - configdata
    - gh-pages

environment:
  matrix:
  - IdeVersion: VS2015
  #- IdeVersion: Mono
  SKIP_PAUSE: TRUE
  ARCHIVE_WITH_PDB: TRUE

build:
  verbosity: minimal

cache:
  #- packages -> **\packages.config      # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - packages\WiX.3.11.0 -> Setup\packages.config

install:
- cmd: git submodule update --init --recursive
- cmd: |-
    cd Setup
    python set_version_to.py -v %APPVEYOR_BUILD_VERSION% -t %APPVEYOR_BUILD_VERSION%Dev@%APPVEYOR_REPO_COMMIT:~0,5%
    cd ..

build_script:
- ps: |
    Write-Output "Platform: $env:IdeVersion"
    & Setup\BuildInstallers.$env:IdeVersion.cmd
    if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

# scripts to run after tests
after_test:
- ps: |
    & Setup\BuildArtifacts.cmd
    if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

artifacts:
    # upload the generated portable archive only
  - path: 'Setup/GitExtensions-*-Mono.zip'

# here we are going to override common configuration
for:

-
  branches:
    only:
      - /release\/.*/

  artifacts:
    # upload the generated installer
    - path: 'Setup/GitExtensions-*.msi'
